### ISSUE TITLE
CustomError: Invalid 'sku' provided ?

### ISSUE THREAD

**Issue by gopkg-dev** [amz-tools/amazon-sp-api#126]
```js
let res = await sellingPartner.callAPI({
    operation: 'getListingsItem',
    endpoint: 'listingsItems',
    path: {
        sellerId: "xxxxxxxx",
        sku: "iPhone 11 Pro Max/XS Max-2Pack0526"
    },
    query: {
        marketplaceIds: ['A1C3SOZRARQ6R3'],
        includedData: ['summaries', 'attributes', 'procurement', 'fulfillmentAvailability', 'issues']
    },
});
console.log(res);
```

```
CustomError: Invalid 'sku' provided. SKU: iPhone%2011%20Pro%20Max%2FXS%20Max-2Pack0526
    at SellingPartner.callAPI (/Users/user01/Desktop/amazon-sp-api-test/node_modules/amazon-sp-api/lib/SellingPartner.js:597:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /Users/user01/Desktop/amazon-sp-api-test/main.js:16:19 {
  code: 'InvalidInput',
  details: '',
  type: 'error'
}
```

**Comment by amz-tools** [comment]
Hi @gopkg-dev,

just spent some time investigating and found out that its quite an interesting bug. The encoding of the whitespace and the `/` is definitely correct as we can see in the error message you posted (we fixed these issues in version 0.7.0 of the client).

But what we noticed is that the error message we receive is different when we cut off the `0526` in the end:
`CustomError: SKU 'iPhone%2011%20Pro%20Max%2FXS%20Max-2Pack' not found in marketplace`

Thats actually the expected and correct result (since we don't have an SKU by that name). However, once we add any more characters to the SKU (it doesn't matter if its `0526` or anything else) we also start receiving the `Invalid 'sku' provided` error.

The issue here seems to be that Amazon allows SKUs to be only 40 characters long. The original SKU `iPhone 11 Pro Max/XS Max-2Pack0526` is 34 characters long, but the encoded SKU `iPhone%2011%20Pro%20Max%2FXS%20Max-2Pack0526` is 44 characters long. Thats obviously 4 characters above the limit and explains why it fails once we add any character after `iPhone%2011%20Pro%20Max%2FXS%20Max-2Pack`.

So it seems as if Amazon counts the characters before decoding the SKU and as such returns an error of an invalid (too long) SKU although thats actually not the case.

@gopkg-dev, could you [open an issue](https://github.com/amzn/selling-partner-api-docs/issues) with Amazon? I think we should let them know, I wouldn't this is intentional behaviour.

**Comment by vhle-ms** [comment]
FYI - I've raised a ticket a couple of days ago with Amazon. They've responded with the following:

"This is a known issue with our Technical teams, and I've added the examples you've provided to our existing contact with them regarding the issue. I''ll monitor this and let you know when we have more information to share.
"

**Comment by vhle-ms** [comment]
Update from Amazon support:

"Our technical team has completed their review of how the SKUs were being handled through the API, and hope to push updates later in the week that will address the SKU not founds errors. I'll continue monitoring this issue and update you when the it has been completed."

**Comment by vhle-ms** [comment]
Update from Amazon support:

"Our Technical team completed their updates to correctly handle the SKU encoding, and issue should now be resolved."

**Comment by amz-tools** [comment]
Can confirm the issue has been resolved, closing the ticket.

**Comment by SWengineer-A** [comment]
Hey, 
Issue still happened now. 
`Error: Invalid 'sku' provided. SKU: BOWNET-AD-SKU-BN-COMMANDER%20BAG%20ORANGE`
